<header class="page-header">
    <h1><?= $board->name ?><?= ($pageNum>1?' sivu ' . $pageNum:'') ?></h1>
    <h2><?= $board->description ?></h2>
</header>

<?php $this->getPartial('Snippets/PostForm') ?>

<?php foreach($threads as $thread) : ?>
<div class="content-box">
    <h3><a href="/<?= $board->url ?>/<?= $thread->id ?>"><?= $thread->subject ?></a></h3>
    <?php var_dump($thread) ?>
</div>
<?php endforeach ?>
