<header class="page-header">
    <h1><?= $board->name ?><?= ($pageNum>1?' sivu ' . $pageNum:'') ?></h1>
    <h2><?= $board->description ?></h2>
</header>

<?php $this->getPartial('Snippets/PostForm') ?>

<?php foreach($threads as $thread) : ?>
<div class="content-box thread">
    <h3><a href="/<?= $board->url ?>/<?= $thread->id ?>"><?= $thread->subject ?></a></h3>
    <div class="op-post">
        <?php $this->getPartial('Snippets/Post', $thread) ?>
    </div>

    <div class="replies">
        <?php foreach($thread->replies as $reply) : ?>
            <div class="reply">
                <?php $this->getPartial('Snippets/Post', $reply) ?>
            </div>
        <?php endforeach ?>
    </div>
</div>

<?php endforeach ?>
