<?php include($viewFilesPath . '/Snippets/BoardHeader.phtml') ?>
<?php include($viewFilesPath . '/Snippets/BoardNavigation.phtml') ?>

<?php include($viewFilesPath . '/Snippets/PostForm.phtml') ?>

<?php if (!empty($threads)) : ?>
<div class="catalog">
    <?php foreach($threads as $thread) : ?>
        <div class="thread-box" id="thread-<?= $thread->id ?>" data-id="<?= $thread->id ?>">
            <?php include($viewFilesPath . '/Snippets/ThreadSubject.phtml') ?>
            <div class="thread-content">
                <div class="op-post" id="post-<?= $thread->id ?>">
                    <?php $post = $thread ?>
                    <div class="post-buttons">
                        <?php if (!$post->threadId) : ?>
                            <?php if (in_array($post->id, $user->threadHide->threads)) : ?>
                                <button class="button square icon-plus" onclick="restoreThread(<?= $post->id ?>)" title="<?= _('Restore') ?>"></button>
                            <?php else : ?>
                                <button class="button square icon-eye-crossed" onclick="hideThread(<?= $post->id ?>)" title="<?= _('Hide') ?>"></button>
                            <?php endif ?>
                        <?php endif ?>
                        <?php if ($post->userId != $user->id) : ?>
                            <button class="button square icon-flag2" onclick="" title="<?= _('Report') ?>"></button>
                        <?php endif ?>
                        <?php if ($post->userId == $user->id || $user->isMod) : ?>
                            <button class="button square icon-trash2" onclick="deletePost(<?= $post->id ?>)" title="<?= _('Delete') ?>"></button>
                        <?php endif ?>
                    </div>

                    <blockquote class="post">
                        <figure class="post-file thumbnail">
                            <a href="/<?= $board->url ?>/<?= $thread->id ?>">
                                <?php if (!empty($post->file)) : ?>
                                    <?php $src = $staticUrl . '/files/' . $post->file->folder . '/t/' . $post->file->name . '.jpg' ?>
                                <?php else : ?>
                                    <?php $src = $staticUrl . '/img/norppa_ylilauta.svg' ?>
                                <?php endif ?>
                                <img src="<?= $src ?>" alt="">
                            </a>
                        </figure>
                        <?= \YBoard\Library\Text::formatMessage($post->message) ?>
                    </blockquote>
                </div>
                <?php include($viewFilesPath . '/Snippets/ThreadMeta.phtml') ?>
            </div>
        </div>
    <?php endforeach; unset($thread); ?>
</div>
<?php else : ?>
<div class="content-box">
    <h3><?= _('There are no threads here...') ?></h3>
</div>
<?php endif ?>

<?php include($viewFilesPath . '/Snippets/BoardNavigation.phtml') ?>
