<header class="page-header">
    <h1><a href="/<?= $board->url ?>/"><?= htmlspecialchars($board->name) ?></a></h1>
    <h2><?= htmlspecialchars($board->description) ?></h2>
</header>

<div class="content-box thread">
    <h3><?= htmlspecialchars($thread->subject) ?></h3>
    <div class="thread-content">
        <div class="op-post">
            <?php $post = $thread; include($viewFilesPath . '/Snippets/Post.phtml') ?>
        </div>

        <div class="replies">
        <?php foreach($thread->replies as $reply) : ?>
            <div class="reply">
                <?php $post = $reply; include($viewFilesPath . '/Snippets/Post.phtml') ?>
            </div>
        <?php endforeach ?>
        </div>
    </div>
</div>

<?php include($viewFilesPath . '/Snippets/PostForm.phtml') ?>
