<?php include($viewFilesPath . '/Snippets/BoardHeader.phtml') ?>
<?php include($viewFilesPath . '/Snippets/BoardNavigation.phtml') ?>

<div class="content-box thread" id="thread-<?= $thread->id ?>" data-id="<?= $thread->id ?>">
    <h3>
        <?php if ($thread->sticky) : ?>
            <span class="icon pushpin">S</span>
        <?php endif ?>
        <?php if ($thread->locked) : ?>
            <span class="icon lock">L</span>
        <?php endif ?>
        <?= htmlspecialchars($thread->subject) ?>
    </h3>
    <div class="thread-content">
        <div class="op-post" id="post-<?= $thread->id ?>">
            <?php $post = $thread; include($viewFilesPath . '/Snippets/Post.phtml') ?>
        </div>

        <?php include($viewFilesPath . '/Snippets/ThreadMeta.phtml') ?>
        <div class="replies">
        <?php foreach($thread->replies as $reply) : ?>
            <div class="reply" id="post-<?= $reply->id ?>">
                <?php $post = $reply; include($viewFilesPath . '/Snippets/Post.phtml') ?>
            </div>
        <?php endforeach ?>
        </div>
        <div class="thread-buttons"></div>
    </div>

    <?php if (!$thread->locked) : ?>
        <?php include($viewFilesPath . '/Snippets/PostForm.phtml') ?>
    <?php endif ?>
</div>


<?php include($viewFilesPath . '/Snippets/BoardNavigation.phtml') ?>
