<?php include($viewFilesPath . '/Snippets/BoardHeader.phtml') ?>
<?php include($viewFilesPath . '/Snippets/BoardNavigation.phtml') ?>

<div class="content-box thread" data-id="<?= $thread->id ?>">
    <h3><?= htmlspecialchars($thread->subject) ?></h3>
    <div class="thread-content">
        <div class="op-post" id="post-<?= $thread->id ?>">
            <?php $post = $thread; include($viewFilesPath . '/Snippets/Post.phtml') ?>
        </div>

        <div class="thread-meta">
            1920 vastausta, 609 tiedostoa
        </div>
        <div class="replies">
        <?php foreach($thread->replies as $reply) : ?>
            <div class="reply" id="post-<?= $reply->id ?>">
                <?php $post = $reply; include($viewFilesPath . '/Snippets/Post.phtml') ?>
            </div>
        <?php endforeach ?>
        </div>
        <div class="thread-buttons">
            <a class="add-reply toggle-postform" href="javascript:void(showPostForm())"><?= _('Reply to thread') ?></a>
        </div>
    </div>
</div>

<?php include($viewFilesPath . '/Snippets/PostForm.phtml') ?>

<?php include($viewFilesPath . '/Snippets/BoardNavigation.phtml') ?>
