<div class="post-meta">
    <div class="col">
        <div class="user-info">
            <span class="username"><?= htmlspecialchars(\YFW\Library\Text::formatUsername($post->username)) ?></span>
            <?php if ($post->userId == $thread->userId): ?>
                <span class="text-tag op"><?= _('OP') ?></span>
            <?php endif ?>
        </div>
        <div class="post-info">
            <span class="post-time datetime"><?= $post->time ?></span>
            <?php if (!isset($tooltip)): ?>
            <a href="/post-<?= $post->id ?>" class="post-id e-post-reply"><?= _('No.') ?> <?= $post->id ?></a>
            <?php else: ?>
            <a href="/post-<?= $post->id ?>" class="post-id"><?= _('No.') ?> <?= $post->id ?></a>
            <?php endif ?>
        </div>
    </div>
    <?php include($viewFilesPath . '/Snippet/PostButtons.phtml') ?>
</div>

<blockquote class="message">
    <?php if (!empty($post->file)): ?>
        <?php if($post->file->hasThumbnail): ?>
            <?php $paddingBottom = str_replace(',','.', round($post->file->thumbHeight / $post->file->thumbWidth * 100, 4)) ?>
        <?php endif ?>
        <?php $fileUrl = $config['url']['files'] . '/' . $post->file->folder . '/o/' . $post->file->name . '/' . rawurlencode($post->file->displayName) . '.' . $post->file->extension ?>
        <figure class="post-file <?= $post->file->hasThumbnail ? '' : 'no ' ?>thumbnail" data-id="<?= $post->file->id ?>"
            <?php if($post->file->hasThumbnail): ?>style="width:<?= $post->file->thumbWidth ?>px"<?php endif ?>
        >
            <?php if (in_array($post->file->extension, ['m4a', 'mp4'])): ?>
                <a href="<?= $fileUrl ?>" class="media" target="_blank"
                    <?php if($post->file->hasThumbnail): ?>style="padding-bottom:<?= $paddingBottom ?>%"<?php endif ?>
                >
                    <?php if ($post->file->hasThumbnail): ?>
                        <img src="<?= $config['url']['files'] ?>/<?= $post->file->folder ?>/t/<?= $post->file->name ?>.jpg" alt="">
                    <?php else: ?>
                        <span class="no-image icon-music-note"></span>
                    <?php endif ?>
                    <span class="overlay center icon-play"></span>
                    <?php if ($post->file->isGif): ?>
                        <span class="overlay bottom right">GIF</span>
                    <?php else: ?>
                        <?php if ($post->file->hasSound): ?>
                            <span class="overlay bottom right icon-volume-high"></span>
                        <?php else: ?>
                            <span class="overlay bottom right icon-mute"></span>
                        <?php endif ?>
                    <?php endif ?>
                </a>
                <button class="button primary e-stop-media"><?= _('Hide media') ?></button>
            <?php else: ?>
                <a href="<?= $fileUrl ?>" class="image" target="_blank"
                   style="padding-bottom:<?= $paddingBottom ?>%">
                    <img src="<?= $config['url']['files'] ?>/<?= $post->file->folder ?>/t/<?= $post->file->name ?>.jpg" alt="">
                </a>
            <?php endif ?>
            <figcaption>
                <a href="<?= $fileUrl ?>" target="_blank"><?= htmlspecialchars($post->file->displayName) ?></a>
                <span>
                <?php if (!empty($post->file->width)): ?>
                    <?= $post->file->width ?>&times;<?= $post->file->height ?>
                <?php endif ?>
                <?php if (!empty($post->file->duration)): ?>
                    <?= \YFW\Library\Text::formatDuration($post->file->duration) ?>
                <?php endif ?>
                    <?= \YFW\Library\Text::formatBytes($post->file->size) ?>
                    <?= htmlspecialchars(strtoupper($post->file->extension)) ?>
                </span>
            </figcaption>
        </figure>
    <?php endif ?>
    <?= $post->getFormattedMessage($user->id) ?>
</blockquote>

<?php if ($post->postReplies): ?>
<div class="post-replies">
    <?= _('Replies') ?>:
    <?php foreach ($post->postReplies as $postReply): ?>
        <a href="/post-<?= $postReply->postId ?>" data-id="<?= $postReply->postId ?>" class="ref">&gt;&gt;<?= $postReply->postId
            . ($postReply->userId === $user->id ? ' (' . _('You') . ')' : '') ?></a>
    <?php endforeach ?>
</div>
<?php endif ?>
