<?php
header('Content-Type: text/html; charset=utf-8');
header($_SERVER['SERVER_PROTOCOL'] . ' 500 Internal Server Error');
if (empty($_SERVER['HTTP_X_REQUESTED_WITH']) || $_SERVER['HTTP_X_REQUESTED_WITH'] !== 'XMLHttpRequest'): ?>
<!doctype html>
<html>
<head>
    <title>Oh noes! | Ylilauta</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
        html {
            min-height: 100%;
            box-sizing: border-box;
            /* You probably need to change this url... */
            background: #528ac9 url('/static/img/norpat.png') no-repeat 50% 100%;
            margin: 0;
            background-size: 100%;
            font: normal 16px "Segoe UI", "Open Sans", Roboto, -apple-system, BlinkMacSystemFont, Helvetica, sans-serif;
            text-align: center;
            box-shadow: none;
            text-shadow: none;
            color: #fff;
            padding: 40px 0 30% 0;
        }
        h1, h2 { font-weight: lighter }
        h1 { font-size: 3em }
        p { margin: 5px }
    </style>
</head>
<body>

<h1>Voihan pahus! - Oh noes!</h1>
<p>Sisäinen virhe: ES-norppa nukahti! Kokeilethan hetken päästä uudelleen...</p>
<p>Internal error: The ES-seal fell asleep! Please try again in a moment...</p>

</body>
</html>
<?php else: ?>
Voihan pahus! - Oh noes!
Sisäinen virhe: ES-norppa nukahti! Kokeilethan hetken päästä uudelleen...
Internal error: The ES-seal fell asleep! Please try again in a moment...
<?php endif ?>
