<?php header('Content-Type: text/html; charset=utf-8'); ?>
<!doctype html>
<html>
<head>
    <title><?= htmlspecialchars($this->getTitle()) ?></title>

    <meta charset="UTF-8">

    <meta name="robots" content="index, follow">
    <meta name="viewport" content="width=700px, initial-scale=1.0">
    <!--<meta name="viewport" content="width=device-width, initial-scale=1.0">-->

    <base href="<?= $baseUrl ?>">

    <link rel="stylesheet" id="css" href="<?= $staticUrl ?>/css/<?= $stylesheet ?>.css?<?=time()?>"
        data-alt="<?= $staticUrl ?>/css/<?= $altStylesheet ?>.css?<?=time()?>">
    <link rel="icon" sizes="192x192" href="<?= $staticUrl ?>/img/norppa_icon.png">

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.2/toastr.min.js"></script>
    <script src="<?= $staticUrl ?>/js/tooltipster.min.js"></script>

    <script src="<?= $staticUrl ?>/js/scripts.js" defer></script>
    <script>
        <?php // TODO: Move to external file? (Pros: can cache, Cons: requires loading everything twice) ?>
        var config = {
            staticUrl: '<?= $staticUrl ?>',
            csrfToken: '<?= $csrfToken ?>',
            reCaptchaPublicKey: '<?= $reCaptchaPublicKey ?>',
        };
        var messages = {
            loading: '<?= _('Loading...') ?>',
            errorOccurred: '<?= _('An error occurred') ?>',
            logOutConfirm: '<?= _('Log out?') ?>',
            signUp: '<?= _('Sign up') ?>',
            cancel: '<?= _('Cancel') ?>',
            logIn: '<?= _('Log_in') ?>',
            maxSizeExceeded: '<?= _('Your files exceed the maximum upload size.') ?>',
            confirmDelete: '<?= _('Delete post?') ?>',
            postSent: '<?= _('Post sent') ?>',
            postDeleted: '<?= _('Post deleted') ?>',
            confirmUnload: '<?= _('Your message will be lost.') ?>',
            noNewReplies: '<?= _('No new replies') ?>',
            showFullMessage: '<?= _('show full message') ?>',
        };
    </script>
    <?php if ($user->requireCaptcha) : ?>
    <script src="//www.google.com/recaptcha/api.js?render=explicit&amp;onload=renderCaptcha" async defer></script>
    <script>
        function renderCaptcha() {
            grecaptcha.render('post-form-captcha', {
                'sitekey': config.reCaptchaPublicKey
            });
        }
    </script>
    <?php endif ?>
</head>
<body<?= (!empty($bodyClass)?' class="' . $bodyClass . '"':'') ?>>
<div id="sidebar">
    <nav id="main">
        <a href="/" id="logo"><img src="<?= $staticUrl ?>/img/norppa_ylilauta.svg" alt="<?= htmlspecialchars($siteName) ?>"><?= htmlspecialchars($siteName) ?></a>
        <a href="/gold"><?= _('Gold account') ?></a>
        <a href="/faq"><?= _('FAQ') ?></a>
        <a href="/rules"><?= _('Rules') ?></a>
        <a href="/about"><?= _('About') ?></a>
        <a href="/advertising"><?= _('Advertising') ?></a>

        <form id="search" type="post" action="/search" id="cse-search-box2">
            <input name="cx" value="<?= $gCsePartnerPub ?>" type="hidden">
            <input name="cof" value="FORID:10" type="hidden">
            <input name="ie" value="UTF-8" type="hidden">
            <input id="searchfield" name="q" size="24" placeholder="<?= _('Search Ylilauta...') ?>" type="text" required>
            <button id="searchbutton" class="icon-magnifier"></button>
        </form>
    </nav>
    <nav id="user">
    <?php if (!$user->loggedIn) : ?>
        <h3><?= _('Log in') ?></h3>
        <form id="login" action="/scripts/user/login" method="post">
            <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">
            <input type="hidden" name="redirto" value="<?= htmlspecialchars(empty($redirTo)?$_SERVER['REQUEST_URI']:$redirTo) ?>">
            <input type="text" name="username" placeholder="<?= _('Username') ?>" required>
            <input type="password" name="password" placeholder="<?= _('Password') ?>" required>
            <div id="signup-form">
                <input type="password" name="repassword" placeholder="<?= _('Password again') ?>">
                <div id="signup-captcha"></div>
            </div>
            <input type="submit" class="button green" name="login" id="loginbutton" value="<?= _('Log_in') ?>">
        </form>
    <?php else : ?>
        <h3><?= htmlspecialchars($user->username) ?></h3>
    <?php endif ?>
        <div class="buttons">
            <a class="button square icon-user" href="/profile" title="<?= _('Profile') ?>"></a>
            <a class="button square icon-cog" href="/preferences" title="<?= _('Preferences') ?>"></a>
            <button class="button square icon-lamp" onclick="toggleDarkTheme()" title="<?= _('Toggle dark theme') ?>"></button>
            <?php if (!$user->loggedIn) : ?>
                <button onclick="signupForm(this, event)" class="button square icon-user-plus" data-open="false"
                    title="<?= _('Sign up') ?>"></button>
            <?php else : ?>
                <form id="logout" action="/scripts/user/logout" method="post">
                    <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">
                    <button type="submit" class="button square icon-exit" title="<?= _('Log out') ?>"
                        onclick="if(!confirm(messages.logOutConfirm)){return false}"></button>
                </form>
            <?php endif ?>
        </div>
    </nav>
    <nav id="boards">
        <h3><?= _('Discussion boards') ?></h3>
    <?php foreach($boardList as $board) : ?>
        <a href="/<?= htmlspecialchars($board->url) ?>/"
            <?= ($board->nsfw?' class="nsfwboard"':'') ?>><?= htmlspecialchars($board->name) ?><?php if($board->nsfw) :
            ?><span class="text-tag nsfw"><?= _('NSFW') ?></span><?php endif ?></a>
    <?php endforeach ?>
    </nav>
</div>
<div id="content">
    <?= $output ?>
</div>
</body>
</html>
