<?php header('Content-Type: text/html; charset=utf-8'); ?>
<!doctype html>
<html>
<head>
    <title><?= htmlspecialchars($this->getTitle()) ?></title>

    <meta charset="UTF-8">

    <meta name="robots" content="index, follow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#117743">

    <base href="<?= $baseUrl ?>">

    <link rel="stylesheet" class="css" href="<?= $staticUrl ?>/css/<?= $stylesheet ?>.css?<?=time()?>"
        data-cur-alt="<?= $stylesheetVariation ?>" data-alt='<?= $altStylesheets ?>'>
    <?php if ($user->preferences->hideSidebar) : ?>
    <link rel="stylesheet" id="hide-sidebar" href="<?= $staticUrl ?>/css/hide_sidebar.css">
    <?php endif ?>

    <link rel="icon" sizes="192x192" href="<?= $staticUrl ?>/img/norppa_icon.png">

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.2/toastr.min.js"></script>
    <script src="<?= $staticUrl ?>/js/tooltipster.min.js"></script>

    <script src="<?= $staticUrl ?>/js/scripts.js?<?=time()?>" defer></script>
    <script>
        <?php // TODO: Move to external file? (Pros: can cache, Cons: requires loading everything twice) ?>
        var config = {
            staticUrl: '<?= $staticUrl ?>',
            csrfToken: '<?= $csrfToken ?>',
            reCaptchaPublicKey: '<?= $reCaptchaPublicKey ?>',
        };
        var messages = {
            loading: '<?= _('Loading...') ?>',
            undo: '<?= _('Undo') ?>',
            errorOccurred: '<?= _('An error occurred') ?>',
            timeoutWarning: '<?= _('Loading timed out – please check your internet connection') ?>',
            networkError: '<?= _('Network error – please check that you are connected to the internet') ?>',
            logOutConfirm: '<?= _('Log out?') ?>',
            signUp: '<?= _('Sign up') ?>',
            cancel: '<?= _('Cancel') ?>',
            logIn: '<?= _('Log_in') ?>',
            maxSizeExceeded: '<?= _('Your files exceed the maximum upload size.') ?>',
            confirmDeletePost: '<?= _('Delete post?') ?>',
            confirmDeleteFile: '<?= _('Delete file?') ?>',
            postSent: '<?= _('Post sent') ?>',
            postDeleted: '<?= _('Post deleted') ?>',
            fileDeleted: '<?= _('File deleted') ?>',
            postReported: '<?= _('Post reported') ?>',
            threadHidden: '<?= _('Thread hidden') ?>',
            threadRestored: '<?= _('Thread restored') ?>',
            threadLocked: '<?= _('Thread locked') ?>',
            threadUnlocked: '<?= _('Thread unlocked') ?>',
            threadStickied: '<?= _('Thread stickied') ?>',
            threadUnstickied: '<?= _('Thread unstickied') ?>',
            reportCleared: '<?= _('Report cleared') ?>',
            banAdded: '<?= _('Ban added') ?>',
            confirmUnload: '<?= _('Your message will be lost.') ?>',
            noNewReplies: '<?= _('No new replies') ?>',
            showFullMessage: '<?= _('show full message') ?>',
            passwordsDoNotMatch: '<?= _('The two passwords do not match') ?>',
            passwordChanged: '<?= _('Password changed') ?>',
            oldBrowserWarning: '<?= _('You are using an outdated browser which does not support some modern techniques used by this website. Please upgrade your browser.') ?>',
        };
    </script>
    <?php if ($user->requireCaptcha) : ?>
    <script src="//www.google.com/recaptcha/api.js?render=explicit&amp;onload=renderCaptcha" async defer></script>
    <?php endif ?>
</head>
<body<?= (!empty($bodyClass)?' class="' . $bodyClass . '"':'') ?>>

<div id="topbar">
    <button class="sidebar-toggle" onclick="toggleSidebar()"><span class="icon-menu"></span><?= _('Menu') ?></button>
    <div class="buttons"
        ><button id="notifications-button" onclick="getNotifications()" class="icon-alarm" title="<?= _('Notifications') ?>"
            ><span class="unread-notifications unread-count red<?= ($user->notifications->unreadCount==0?' none':'') ?>"
            ><?= $user->notifications->unreadCount ?></span></button
        ><a href="/followedthreads/" class="icon-bookmark2" title="<?= _('Followed threads') ?>"><?php
            if($user->threadFollow->unreadCount != 0) :
                ?><span class="unread-count green"><?= $user->threadFollow->unreadCount ?></span><?php
            endif ?></a
        ><button onclick="$(document).scrollTop($('body').height())" class="icon-enter-down2" title="<?= _('Go to bottom') ?>"></button
        ><button onclick="$(document).scrollTop(0)" class="icon-enter-up2" title="<?= _('Back to top') ?>"></button
        ><button onclick="pageReload()" class="icon-sync" title="<?= _('Refresh page') ?>"></button
    ></div>
</div>

<?php include($viewFilesPath . '/Snippets/Sidebar.phtml') ?>

<div id="content">
    <?php if ($user->ban) : ?>
    <div id="banned">
        <h3><?= _('You are banned!') ?></h3>
        <p>
            <?= sprintf(_('Reason: %s'), $user->ban->getReasonText()) ?>
            <?= (empty($user->ban->additionalInfo)?'':', ' . $user->ban->additionalInfo) ?>
        </p>
        <p>
            <?= sprintf(_('Your ban ends: %s'), '<span class="datetime">' . $user->ban->endTime . '</span>') ?>
        </p>
        <?php if ($user->ban->messageFrom) : ?>
            <p class="tooltip" title="<?= htmlspecialchars($user->ban->messageFrom) ?>"
            ><?= _('Click here to see the post that resulted in this ban.') ?></p>
        <?php endif ?>
        <?php if ($user->ban->userId != $user->id) : ?>
        <p><?= _('This ban was not given to your user account, but to someone near you.') ?></p>
        <?php endif ?>
    </div>
    <?php endif ?>
    <?= $output ?>
</div>
<div id="modal-root"></div>
</body>
</html>
