<?php header('Content-Type: text/html; charset=utf-8'); ?>
<!doctype html>
<html>
<head>
    <title>???</title>

    <meta charset="UTF-8">

    <meta name="robots" content="index, follow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <base href="<?= $baseUrl ?>">

    <link rel="stylesheet" href="<?= $staticUrl ?>/css/ylilauta.css">
    <link rel="icon" href="<?= $staticUrl ?>/img/favicon.png">

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <script defer src="<?= $staticUrl ?>/js/scripts.js"></script>
    <script>
        var config = {
            csrfToken: 'nope',
        };
    </script>
</head>
<body>

<div id="wrap">
    <div id="content"><?= $output ?></div>
</div>
</body>
</html>
