<header class="page-header">
    <div class="board-title">
        <h1><a href="/<?= $board->url ?>/"><?= htmlspecialchars($board->name) ?></a><?php if ($board->isNsfw) : ?><span class="text-tag nsfw"><?= _('NSFW') ?></span><?php endif ?></h1>
        <h2><?= htmlspecialchars($board->description) ?></h2>
    </div>
    <div class="buttons">
        <?php if (empty($thread)) : ?>
        <button class="button green create-thread toggle-postform" onclick="showPostForm()"><?= _('Create a thread') ?></button>
        <?php elseif (!$thread->locked) : ?>
        <button class="button green add-reply toggle-postform" onclick="showPostForm()"><?= _('Reply to thread') ?></button>
        <?php endif ?>
    </div>
</header>
