<div class="board-navigation">
    <div class="breadcrumb">
        <a href="/"><?= htmlspecialchars($siteName) ?></a>
        <div class="sep">&raquo;</div>
        <a href="/<?= $board->url ?>/"><?= htmlspecialchars($board->name) ?></a>
        <?php if(!empty($thread->id)) : ?>
            <div class="sep">&raquo;</div>
            <a href="/<?= $board->url ?>/<?= $thread->id ?>"><?= htmlspecialchars($thread->subject) ?></a>
        <?php endif ?>
    </div>
    <?php if (empty($thread->id)) : ?>
    <div class="pagination">
        <?php if ($pageNum == 2) : ?>
            <a href="/<?= $board->url . $paginationBase ?>/" class="icon icon-chevron-left chevron"></a>
        <?php elseif ($pageNum > 2) : ?>
            <a href="/<?= $board->url . $paginationBase ?>-<?= $pageNum-1 ?>/" class="icon icon-chevron-left chevron"></a>
        <?php endif ?>
        <?php if ($paginationStartPage > 1) : ?>
            <a href="/<?= $board->url . $paginationBase ?>/"<?= ($pageNum==1?' class="cur"':'') ?>>1</a>
            <?php if ($paginationStartPage > 2) : ?>
            <span class="sep">&hellip;</span>
            <?php endif ?>
        <?php endif ?>

        <?php for ($i = $paginationStartPage; $i <= $paginationEndPage; ++$i) : ?>
            <a href="/<?= $board->url . $paginationBase ?>-<?= $i ?>/"<?= ($pageNum==$i?' class="cur"':'') ?>><?= $i ?></a>
        <?php endfor ?>
        <?php if ($pageNum < $maxPages) : ?>
            <a href="/<?= $board->url . $paginationBase ?>-<?= $pageNum+1 ?>/" class="icon icon-chevron-right chevron"></a>
        <?php endif ?>
        <div class="display-styles">
            <a href="/<?= $board->url ?>/" class="icon-list4"></a>
            <a href="/<?= $board->url ?>/catalog/" class="icon-grid"></a>
        </div>
    </div>
    <?php endif ?>
</div>
