<form id="post-form" action="/scripts/posts/submit" method="post" onsubmit="submitPost(event)">
    <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">
<?php if (!empty($thread->id)) : ?>
    <h3><?= _('Submit a reply') ?></h3>
    <input type="hidden" id="post-destination" name="thread" value="<?= $thread->id ?>">
<?php else : ?>
    <h3><?= _('Create a thread') ?></h3>
    <input type="hidden" id="post-destination" name="board" value="<?= $board->url ?>">
    <label id="label-subject">
        <span><?= _('Subject') ?></span>
        <input type="text" name="subject" placeholder="<?= _('Subject') ?>">
    </label>
<?php endif ?>
    <label id="label-file">
        <?php // TODO: change accept and max file size ?>
        <span><?= _('File') ?> <span><<?= \YBoard\Library\Text::formatBytes($uploadMaxSize) ?></span></span>
        <input type="file" name="files" id="post-files" accept="*.*" data-maxsize="<?= $uploadMaxSize ?>">
    </label>

    <div id="message-input">
        <div id="format-toolbar">
            <a class="icon-bold" onclick="addBbCode('b')"></a>
            <a class="icon-italic" onclick="addBbCode('em')"></a>
            <a class="icon-strikethrough" onclick="addBbCode('s')"></a>
            <a class="icon-underline" onclick="addBbCode('u')"></a>
            <a class="icon-eye-crossed" onclick="addBbCode('spoiler')"></a>
            <a class="icon-plus" onclick="addBbCode('big')"></a>
            <a class="icon-minus" onclick="addBbCode('small')"></a>
            <a class="icon-bubble-quote" onclick="addBbCode('quote')"></a>
            <a class="icon-code" onclick="addBbCode('code')"></a>
            <a class="icon-superscript" onclick="addBbCode('sup')"></a>
            <a class="icon-subscript" onclick="addBbCode('sub')"></a>
            <a class="icon-palette" onclick="$('#colorbuttons').toggle()"></a>
            <a class="icon-popout right" onclick="$('#post').toggleClass('asyncreply')"></a>
            <div id="colorbuttons" style="display: none;">
                <a class="icon-palette black" onclick="addBbCode('black')"></a>
                <a class="icon-palette gray" onclick="addBbCode('gray')"></a>
                <a class="icon-palette white" onclick="addBbCode('white')"></a>
                <a class="icon-palette brown" onclick="addBbCode('brown')"></a>
                <a class="icon-palette red" onclick="addBbCode('red')"></a>
                <a class="icon-palette orange" onclick="addBbCode('orange')"></a>
                <a class="icon-palette yellow" onclick="addBbCode('yellow')"></a>
                <a class="icon-palette green" onclick="addBbCode('green')"></a>
                <a class="icon-palette blue" onclick="addBbCode('blue')"></a>
                <a class="icon-palette purple" onclick="addBbCode('purple')"></a>
                <a class="icon-palette pink" onclick="addBbCode('pink')"></a>
            </div>
        </div>
        <textarea name="message" placeholder="<?= _('Message') ?>"></textarea>
        <div id="post-progress"><div></div></div>
    </div>

    <?php if (!$user->loggedIn) : ?>
    <div id="post-form-captcha"></div>
    <?php endif ?>
    <button onclick="event.preventDefault();$('#post-options').toggle()" class="button gray"><?= _('Options') ?></button>
    <button id="reset-button" onclick="event.preventDefault();resetPostForm()" class="button gray"><?= _('Cancel') ?></button>
    <input type="submit" class="button green" value="<?= _('Submit') ?>">
    <div id="post-options">
        <h4><?= _('Functions') ?></h4>
        <label>
            <input type="checkbox" name="sage">
            <?= _('Don\'t bump the thread') ?>
        </label>
        <label>
            <input type="checkbox" name="hidename">
            <?= _('Hide your name') ?>
        </label>
        <h4><?= _('Gold account functions') ?></h4>
        <label>
            <input type="checkbox" name="nocompress">
            <?= _('Keep original file dimensions') ?>
        </label>
        <label>
            <input type="checkbox" name="goldonly">
            <?= _('Hide message from non-golds') ?>
        </label>
    </div>
</form>
