<div class="post-buttons">
    <?php if (!$thread->locked || $user->isMod) : ?>
        <button class="button square icon-bubbles" onclick="replyToPost(<?= $post->id ?>)" title="<?= _('Reply') ?>"></button>
    <?php endif ?>
    <!--
    <a href="#"><?= _('Donate gold') ?></a>
    -->
    <?php if (!$post->threadId) : ?>
        <?php if (!$user->threadHide->exists($post->id)) : ?>
            <button class="button square icon-eye-crossed" onclick="hideThread(<?= $post->id ?>)" title="<?= _('Hide') ?>"></button>
        <?php else : ?>
            <button class="button square icon-eye" onclick="restoreThread(<?= $post->id ?>)" title="<?= _('Restore') ?>"></button>
        <?php endif ?>
        <?php if (!$user->threadFollow->exists($post->id)) : ?>
            <button class="button square icon-bookmark-add followbutton" onclick="followThread(<?= $post->id ?>)" title="<?= _('Follow') ?>"></button>
        <?php else : ?>
            <button class="button square icon-bookmark-remove followbutton" onclick="unfollowThread(<?= $post->id ?>)" title="<?= _('Unfollow') ?>"></button>
        <?php endif ?>
    <?php endif ?>
    <button class="button square icon-flag2" onclick="reportPost(this, <?= $post->id?>)" title="<?= _('Report') ?>"></button>
    <?php if ($user->isMod) : ?>
        <button class="mod-menu button square icon-wrench" data-ip="<?= $post->ip ?>" data-uid="<?= $post->userId ?>"
                data-is-reply="<?= (!empty($post->threadId)?'true':'false') ?>"
                onclick="openModMenu(this, <?= $post->id ?>)" title="<?= _('Moderation') ?>"></button>
        <div class="mod-menu-html">
            <p><?= _('IP') ?>: <?= $post->ip ?> (<?= $post->countryCode ?>)</p>
            <p><?= _('User ID') ?>: <a href="/profile/<?= $post->userId ?>"><?= $post->userId ?></a></p>
            <?php if(!empty($post->file)) : ?>
                <p><button onclick="deleteFile(<?= $post->id ?>)" class="link"><?= _('Delete file from post') ?></button></p>
            <?php endif ?>
            <p><button onclick="deletePost(<?= $post->id ?>)" class="link"><?= _('Delete post') ?></button></p>
        </div>
    <?php else : ?>
        <?php if ($post->userId != $user->id) : ?>
        <?php else : ?>
            <button class="button square icon-trash2" onclick="deletePost(<?= $post->id ?>)" title="<?= _('Delete') ?>"></button>
        <?php endif ?>
    <?php endif ?>
</div>
