<div class="post-buttons">
    <?php if (!$thread->locked) : ?>
    <button class="link" onclick="replyToPost(<?= $post->id ?>)"><?= _('reply') ?></button>
    <?php endif ?>
    <!--
    <a href="#"><?= _('gold') ?></a>
    -->
    <button class="link" onclick=""><?= _('hide') ?></button>
    <button class="link" onclick=""><?= _('report') ?></button>
    <?php if ($post->userId == $user->id || $user->isMod) : ?>
    <button class="link" onclick="deletePost(<?= $post->id ?>)"><?= _('delete') ?></button>
    <?php endif ?>
</div>

<div class="post-meta">
    <div class="user-info">
        <span class="username"><?= htmlspecialchars($post->username) ?></span>
        <?php if ($post->userId == $thread->userId) : ?>
            <span class="text-tag op"><?= _('OP') ?></span>
        <?php endif ?>
    </div>
    <div class="post-info">
        <span class="post-time datetime"><?= $post->time ?></span>
        <a href="/<?= $board->url ?>/<?= $thread->id ?>#post-<?= $post->id ?>"
            onclick="<?php if (!$thread->locked) : ?>replyToPost(<?= $post->id ?>);<?php endif ?>return false"
            class="post-id"><?= _('No.') ?> <?= $post->id ?></a>
    </div>
</div>
<blockquote class="post">
    <?php if (!empty($post->file)) : ?>
    <?php $fileUrl = $staticUrl . '/files/' . $post->file->folder . '/o/' . $post->file->name . '/' . rawurlencode($post->file->displayName) . '.' . $post->file->extension; ?>
    <figure class="post-file thumbnail">
        <a href="<?= $fileUrl ?>" onclick="expandImage(this, event)">
            <img src="<?= $staticUrl ?>/files/<?= $post->file->folder ?>/t/<?= $post->file->name ?>.jpg" alt="">
        </a>
        <figcaption>
            <a href="<?= $fileUrl ?>" target="_blank"><?= htmlspecialchars($post->file->displayName) ?></a>
            <span><?= \YBoard\Library\Text::formatBytes($post->file->size) ?> <?= htmlspecialchars(strtoupper($post->file->extension)) ?></span>
        </figcaption>
    </figure>
    <?php endif ?>
    <?= $post->messageFormatted ?>
</blockquote>
