<form id="post-form" action="/scripts/posts/submit" method="post" onsubmit="submitPost(event)">
    <fieldset>
<?php if (!empty($thread->id)) : ?>
    <h3><?= _('Submit a reply') ?></h3>
    <input type="hidden" id="post-destination" name="thread" value="<?= $thread->id ?>">
<?php else : ?>
    <h3><?= _('Create a thread') ?></h3>
    <input type="hidden" id="post-destination" name="board" value="<?= $board->url ?>">
    <label id="label-subject">
        <span><?= _('Subject') ?></span>
        <input type="text" name="subject" placeholder="<?= _('Subject') ?>" maxlength="<?= $subjectMaxLength ?>">
    </label>
<?php endif ?>
    <label id="label-file">
        <span><?= _('File') ?> <span><<?= \YBoard\Library\Text::formatBytes($uploadMaxSize) ?></span></span>
        <input type="file" name="files" id="post-files" accept="<?= $acceptedFileTypes ?>" data-maxsize="<?= $uploadMaxSize ?>">
    </label>

    <div id="message-input">
        <div id="format-toolbar">
            <a class="icon-bold" title="<?= _('Bold') ?>" onclick="addBbCode('b')"></a>
            <a class="icon-italic" title="<?= _('Italic') ?>" onclick="addBbCode('em')"></a>
            <a class="icon-strikethrough" title="<?= _('Strikethrough') ?>" onclick="addBbCode('s')"></a>
            <a class="icon-underline" title="<?= _('Underline') ?>" onclick="addBbCode('u')"></a>
            <a class="icon-spoiler" title="<?= _('Spoiler') ?>" onclick="addBbCode('spoiler')"></a>
            <a class="icon-font-small" title="<?= _('Small text') ?>" onclick="addBbCode('small')"></a>
            <a class="icon-font-big" title="<?= _('Big text') ?>" onclick="addBbCode('big')"></a>
            <a class="icon-bubble-quote" title="<?= _('Quote') ?>" onclick="addBbCode('quote')"></a>
            <a class="icon-code" title="<?= _('Code') ?>" onclick="addBbCode('code')"></a>
            <a class="icon-superscript" title="<?= _('Superscript') ?>" onclick="addBbCode('sup')"></a>
            <a class="icon-subscript" title="<?= _('Subscript') ?>" onclick="addBbCode('sub')"></a>
            <a class="icon-palette" title="<?= _('Colors') ?>" onclick="$('#color-buttons').toggle()"></a>
            <div id="color-buttons" style="display:none">
                <a class="icon-palette black" title="<?= _('Black') ?>" onclick="addBbCode('black')"></a>
                <a class="icon-palette gray" title="<?= _('Gray') ?>" onclick="addBbCode('gray')"></a>
                <a class="icon-palette white" title="<?= _('White') ?>" onclick="addBbCode('white')"></a>
                <a class="icon-palette brown" title="<?= _('Brown') ?>" onclick="addBbCode('brown')"></a>
                <a class="icon-palette red" title="<?= _('Red') ?>" onclick="addBbCode('red')"></a>
                <a class="icon-palette orange" title="<?= _('Orange') ?>" onclick="addBbCode('orange')"></a>
                <a class="icon-palette yellow" title="<?= _('Yellow') ?>" onclick="addBbCode('yellow')"></a>
                <a class="icon-palette green" title="<?= _('Green') ?>" onclick="addBbCode('green')"></a>
                <a class="icon-palette blue" title="<?= _('Blue') ?>" onclick="addBbCode('blue')"></a>
                <a class="icon-palette purple" title="<?= _('Purple') ?>" onclick="addBbCode('purple')"></a>
                <a class="icon-palette pink" title="<?= _('Pink') ?>" onclick="addBbCode('pink')"></a>
            </div>
        </div>
        <textarea name="message" placeholder="<?= _('Message') ?>" maxlength="<?= $messageMaxLength ?>"></textarea>
        <div id="post-progress"><div></div></div>
    </div>

    <?php if ($user->requireCaptcha) : ?>
    <div id="post-form-captcha"></div>
    <?php endif ?>
    <button onclick="$('#post-options').toggle();return false" class="button gray"><?= _('Options') ?></button>
    <button id="reset-button" onclick="resetPostForm();return false" class="button gray"><?= _('Cancel') ?></button>
    <input type="submit" class="button green" value="<?= _('Submit') ?>">
    <div id="post-options">
        <h4><?= _('Functions') ?></h4>
        <label>
            <input type="checkbox" name="sage">
            <?= _('Don\'t bump the thread') ?>
        </label>
        <label>
            <input type="checkbox" name="hidename">
            <?= _('Hide your name') ?>
        </label>
        <h4><?= _('Gold account functions') ?></h4>
        <label>
            <input type="checkbox" name="nocompress">
            <?= _('Keep original file dimensions') ?>
        </label>
        <label>
            <input type="checkbox" name="goldonly">
            <?= _('Hide message from non-golds') ?>
        </label>
    </div>
    </fieldset>
</form>
